name: "TMDb Trailers"
guid: "69104C31-D23F-4040-B99C-8913C09751D6"
version: "untagged-29332c2282dd26359c50"
targetAbi: "10.9.11.0"
framework: "net8.0"
owner: "crobibero"
overview: "Watch trailers from TMDb"
imageUrl: "https://raw.githubusercontent.com/crobibero/jellyfin-plugin-tmdb-trailers/master/Jellyfin.Plugin.Tmdb.Trailers/Images/jellyfin-plugin-tmdb.png"
description: >
  Watch trailers from TMDb

category: "Channels"
artifacts:
  - "Jellyfin.Plugin.Tmdb.Trailers.dll"
  - "TMDbLib.dll"
  - "AngleSharp.dll"
  - "CliWrap.dll"
  - "YoutubeExplode.dll"
  - "YoutubeExplode.Converter.dll"
changelog: |-
  - Update actions/checkout digest to eef6144 - autoclosed (#126) @renovate
  - Update actions/upload-artifact action to v4.4.3 (#127) @renovate
  - Update Youtube to 6.4.3 (#125) @renovate
  - Update Youtube to 6.4.1 (#124) @renovate
  - Update Youtube to 6.4.0 (#123) @renovate
  - Update actions/setup-dotnet digest to 6bd8b7f (#122) @renovate
  - Update CI dependencies (#121) @renovate
  - chore(deps): update oddstr13/jellyfin-plugin-repository-manager action to v1.1.1 (#119) @renovate
  - chore(deps): update actions/checkout digest to 692973e (#117) @renovate
  - chore(deps): update youtube to v6.3.16 (#118) @renovate
  - chore(deps): update youtube to v6.3.15 (#111) @renovate
