name: "TMDb Trailers"
guid: "69104C31-D23F-4040-B99C-8913C09751D6"
version: "untagged-29332c2282dd26359c50"
targetAbi: "10.9.7.0"
framework: "net8.0"
owner: "crobibero"
overview: "Watch trailers from TMDb"
imageUrl: "https://raw.githubusercontent.com/crobibero/jellyfin-plugin-tmdb-trailers/master/Jellyfin.Plugin.Tmdb.Trailers/Images/jellyfin-plugin-tmdb.png"
description: >
  Watch trailers from TMDb

category: "Channels"
artifacts:
  - "Jellyfin.Plugin.Tmdb.Trailers.dll"
  - "TMDbLib.dll"
  - "AngleSharp.dll"
  - "CliWrap.dll"
  - "YoutubeExplode.dll"
  - "YoutubeExplode.Converter.dll"
changelog: |-
  - chore(deps): update oddstr13/jellyfin-plugin-repository-manager action to v1.1.1 (#119) @renovate
  - chore(deps): update actions/checkout digest to 692973e (#117) @renovate
  - chore(deps): update youtube to v6.3.16 (#118) @renovate
  - chore(deps): update youtube to v6.3.15 (#111) @renovate
