name: "TMDb Trailers"
guid: "69104C31-D23F-4040-B99C-8913C09751D6"
version: "13"
targetAbi: "10.9.0.0"
framework: "net8.0"
owner: "crobibero"
overview: "Watch trailers from TMDb"
imageUrl: "https://raw.githubusercontent.com/crobibero/jellyfin-plugin-tmdb-trailers/master/Jellyfin.Plugin.Tmdb.Trailers/Images/jellyfin-plugin-tmdb.png"
description: >
  Watch trailers from TMDb

category: "Channels"
artifacts:
  - "Jellyfin.Plugin.Tmdb.Trailers.dll"
  - "TMDbLib.dll"
  - "AngleSharp.dll"
  - "CliWrap.dll"
  - "YoutubeExplode.dll"
  - "YoutubeExplode.Converter.dll"
changelog: |-
  - chore(deps): update actions/checkout digest to 0ad4b8f (#114) @renovate
  - chore(deps): update ci dependencies (#110) @renovate
  - chore(deps): update youtube to v6.3.12 (#101) @renovate
  - chore(deps): update dependency tmdblib to v2.1.0 (#102) @renovate
  - chore(deps): update actions/setup-dotnet action to v4 (#103) @renovate
  - chore(deps): update oddstr13/jellyfin-plugin-repository-manager action to v1.0.12 (#104) @renovate
  - chore(deps): update actions/upload-artifact action to v4 - autoclosed (#105) @renovate
  - chore(deps): update dependency stylecop.analyzers to v1.2.0-beta.556 (#106) @renovate
  - chore(deps): update youtube to v6.3.7 (#99) @renovate
  - chore(deps): update ci dependencies (#92) @renovate
  - chore(deps): update dependency tmdblib to v2 (#82) @renovate
  - chore(deps): update dependency microsoft.codeanalysis.netanalyzers to v7.0.4 (#83) @renovate
  - chore(deps): update actions/checkout digest to b4ffde6 (#94) @renovate
  - chore(deps): update oddstr13/jellyfin-plugin-repository-manager action to v1 (#95) @renovate
  - chore(deps): update youtube to v6.3.6 (#97) @renovate
  - chore(deps): update youtube to v6.3.5 (#93) @renovate
  - chore(deps): update youtube to v6.3.3 (#79) @renovate
  - chore(deps): update actions/setup-dotnet digest to 3447fd6 (#80) @renovate
  - chore(deps): update dependency stylecop.analyzers to v1.2.0-beta.507 - autoclosed (#84) @renovate
  - chore(deps): update shogo82148/actions-upload-release-asset action to v1.6.6 (#85) @renovate
  - chore(deps): update actions/checkout action to v4 (#90) @renovate
